QAPPLICATION_ID = "c3b1409d-664b-400c-a52f-1501742dee4e"
IAM_ROLE = "arn:aws:iam::654654371288:role/qupdatedflow-template-EC2ServiceRole-cK1bsHcfN7nc"
REGION = "us-west-2"
IDC_APPLICATION_ID = "arn:aws:sso::654654371288:application/ssoins-7907b281e4f89494/apl-a61325746d7d9675"
CognitoDomain = "qupdatedflow-dns-testname.auth.us-west-2.amazoncognito.com"
ClientId= "42t68fhbdaf2p7uffm2ends5jb"
ExternalDns = "qupdat-appli-dpe5qO6r8u1a-1044258827.us-west-2.elb.amazonaws.com"

