QAPPLICATION_ID = "c3b1409d-664b-400c-a52f-1501742dee4e"
IAM_ROLE = "arn:aws:iam::654654371288:role/qcustomflow-template-QServiceRole-bCD4NBtKSwGK"
REGION = "us-west-2"
IDC_APPLICATION_ID = "arn:aws:sso::654654371288:application/ssoins-7907b281e4f89494/apl-c8a1bbfded9faacc"
CognitoDomain = "qcustomflow-dns-testname.auth.us-west-2.amazoncognito.com"
ClientId= "2iem3v1frbh6ve11fa17mhi7ub"
ExternalDns = "qcusto-appli-f7kexo4aarzv-1168257116.us-west-2.elb.amazonaws.com"